spring:
    application:
        name: cashregister
    datasource:
        url: jdbc:postgresql://localhost:5432/cash_register
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              format_sql: true


application:
    security:
        jwt:
            secret-key: <key>
            refresh-secret-key: <refresh-key>
            expiration-time: 300000
            refresh-expiration-time: 120000000
        cors:
            allowed-origin: <allowed origin>